# Generated by Django 5.2.1 on 2025-05-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together={("name", "measurement_unit")},
        ),
    ]
